server:
  port: 8080
  development: true
database:
  #IPv6 addresses should be wrapped in brackets e.g. [::]
  host: localhost
  port: 5432
  database: set321go
  schema: profiles
  username: set321go
  password:
#Application configuration, defaults shown
#application:
#  location: http://<host string>/
